package com.demo.common.model;

import com.demo.common.model.base.BaseMallGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MallGoods extends BaseMallGoods<MallGoods> {
	
}
